services:
  mysql:
    build:
      context: './mysql'
      dockerfile: 'Dockerfile'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}:/var/lib/mysql'
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    build:
      context: './phpmyadmin'
      dockerfile: 'Dockerfile'
    environment:
      - 'PMA_ARBITRARY=0'
      - 'PMA_HOST=${CONTAINER_PREFIX}-mysql-1'
      - 'PMA_USER=${DB_USER}'
      - 'PMA_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    ports:
      - '${PMA_PORT}:80'
volumes:
      {}
