services:
  mysql:
    build:
      context: './mysql'
      dockerfile: 'Dockerfile'
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - '${DATA_PATH_HOST}:/var/lib/mysql'
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    build:
      context: './phpmyadmin'
      dockerfile: 'Dockerfile'
      args:
        PHP_MY_ADMIN_VERSION: ${PHP_MY_ADMIN_VERSION}
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: ${CONTAINER_PREFIX}-mysql-1
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '${PMA_PORT}:80'
