#User defined
user:
  mysql_version:
    label:
      MySQL version
    hint:
      Select MySQL version
    type:
      select
    values:
      - "5.7"
      - "8"
      - "8.4.4"
      - "9.2"
    target:
      MYSQL_VERSION

  php_my_admin_version:
    label:
      PHP my admin version
    hint:
      Select PHP my admin version
    type:
      select
    values:
      - "5.0"
      - "5.2.2"
    target:
      PHP_MY_ADMIN_VERSION

#System defaults
system:
  db_credentials:
    true
  #Generate public ports for the docker image
  ports:
    http:
      PMA_PORT
    others:
      - MYSQL_PORT


